### ISSUE TITLE
Setup CI for pana

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#1077]
A CI for https://github.com/dart-lang/pana should be setup to ensure the quality of our packages is good.

Currently broken because of https://github.com/dart-lang/pana/pull/1212 which is fixed, but only in a version that breaks our dependency constraints...

**Comment by provokateurin** [comment]
Without https://github.com/dart-lang/pana/issues/1020 we can't really use it in CI because the static code analysis will fail once there are breaking changes because it doesn't consider the dependency_overrides.

**Comment by Leptopoda** [comment]
Not feasible for every PR.
We should run it before every package is released.
