### ISSUE TITLE
Merge oneOf double|int to num

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#1082]
num has the usecase of representing double and int and we can perfectly use it here.

**Comment by Leptopoda** [comment]
If we don't fix this in time for https://github.com/nextcloud/neon/milestone/4 we can just patch the specs and introduce this later.

I can image this not being that trivial.

**Comment by Leptopoda** [comment]
Just adding that this should be optional and configurable within the dynamite config.
