### ISSUE TITLE
Document dynamite packages

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1088]
Extracted from #692 
- [ ] add examples
- [x] update READMEs
- [x] add getting started guides

Document Licensing. With #1083  one can include rely on dynamite (and dynamite_runtime) in a closed source environment but would still need to publish changes to dynamite itself.

**Comment by Leptopoda** [comment]
For the example our petstore package should be used.
Sadly we can not symlink it into place so we'll need a to copy it in place before publishing (either manually or better with a script)

**Comment by provokateurin** [comment]
This can be closed, right?
