### ISSUE TITLE
Use UriTemplates for the Uris

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1097]
We currently query encode path parameters which is not required by the openapi specification. Only query parameters need to be:

```dart
    final x0 = Uri.encodeQueryComponent(x.toString());
    final y0 = Uri.encodeQueryComponent(y.toString());
	[...]
    final file0 = Uri.encodeQueryComponent(file);
    final path = '/index.php/apps/files/api/v1/thumbnail/$x0/$y0/$file0';
    final uri = Uri(path: path, queryParameters: queryParameters.isNotEmpty ? queryParameters : null);
```

https://swagger.io/docs/specification/serialization/ has a table on how to interpret parameter specifications as an RFC 6570 uri template. The google published dart library `uri` already supports these templates (https://pub.dev/documentation/uri/latest/uri/UriTemplate-class.html) so switching to them might:
- widen the supported parameter serialization types
- give us the confidence that we do it correctly
- maybe reduce complexity of our code as we'd only have a template and a collection of values to substitude

@provokateurin what do you think? Shouldn't be that hard.

**Comment by provokateurin** [comment]
Oh that sounds very good, I assume it will also already handle the URL encoding for us?

**Comment by Leptopoda** [comment]
I think this is part of the RFC specification.
Let's see

**Comment by provokateurin** [comment]
@Leptopoda May I take this issue over? You already have so much dynamite work on your plate

**Comment by Leptopoda** [comment]
sure

**Comment by provokateurin** [comment]
Later on we should also use the UriTemplates for query parameters.

**Comment by provokateurin** [comment]
Unassigning myself for now

**Comment by Leptopoda** [comment]
removing from the milestone as we now no longer incorrectly encode path parameters.

**Comment by Leptopoda** [comment]
the pr didn't auto close this issue :(
closing as done.
