### ISSUE TITLE
Dart tests never run on merge commits

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#1110]
The diff fails silently (1. problem) and then no tests are ran (2. problem). See https://github.com/nextcloud/neon/actions/runs/6755679877/job/18364347890 for example.

**Comment by provokateurin** [comment]
We might just want to disable them on the main branch and only run them on pull requests to save CI time (since every commit already has to pass the tests while it is still a PR). @Leptopoda what do you think?

**Comment by Leptopoda** [comment]
let's do that :+1:
