### ISSUE TITLE
UnifiedPush distributors not being detected

### ISSUE THREAD

**Issue by nr23730** [nextcloud/neon#1115]
Hi,

on my device I was not able to set up notifications using UnifiedPush. The settings page shows the message about no provider being detected in red letters. However, I explicitly enabled notifications for Neon in system settings.
I have NextPush installed on my device (it's also on the same Nextcloud of which I added the account). For testing purposes I also installed ntfy, which also was not detected. Other apps (Element, Tusky) successfully detect them on my phone.

This is the artifact that I used: https://github.com/nextcloud/neon/actions/runs/6761285414

My phone is a Pixel 6 running Android 14 (GrapheneOS, no GApps installed).

**Comment by provokateurin** [comment]
Thanks for the report, I'll look into it

**Comment by nr23730** [comment]
Works fine! Thank you very much!
