### ISSUE TITLE
Find and test naming collisions and string escaping within dynamite

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1154]
continuation of #1099

**Comment by Leptopoda** [comment]
Issues:
- [ ] `Object` is considered a valid class name. This will not produce a compile time error but is fairly inconvenient to use.

**Comment by provokateurin** [comment]
Enum generation ignores keywords in class name:
```json
"String": {
    "type": "string",
    "enum": [
        "a",
        "b",
        "c"
    ]
},
```
leads to
```dart
class String extends EnumClass {
  const String._(super.name);

  static const String a = _$stringA;

  static const String b = _$stringB;

  static const String c = _$stringC;

  static BuiltSet<String> get values => _$stringValues;

  static String valueOf(final String name) => _$valueOfString(name);

  static Serializer<String> get serializer => _$stringSerializer;
}
```
This might apply to normal object generation as well.

**Comment by Leptopoda** [comment]
We should also document that we require class names to be unique when parsed to be camelCase.

There is no way we can reasonably support both a  'my-class' and 'MyClass' in the same spec.

**Comment by provokateurin** [comment]
Interfaces getters need to be escaped as well (otherwise built_value generates broken code).

**Comment by Leptopoda** [comment]
since https://github.com/nextcloud/neon/pull/1276 we can conflict with our serializers.

**Comment by Leptopoda** [comment]
RegExp is another class name that need sescaping
