### ISSUE TITLE
Discuss used lint rules

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1245]
We currently enable the `prefer_final_parameters` rule this is not common in dart and also affects #1244.
Disabling it should not affect performance or code size (to be investigated) and for `parameter_assignments` has us covered for the rest.

**Comment by provokateurin** [comment]
And instead we enable `avoid_final_parameters`, right?

**Comment by Leptopoda** [comment]
I did some testing a few days ago and as expected I was not able to find any difference.
Sadly from a `avoid_final_parameters` does not have a quick fix so I'd just disable it in the generated code for now. And the rest can be migrated in the future (if we really want to).

On a side note should we also ignore `no_leading_underscores_for_local_identifiers` in our generated code?

**Comment by provokateurin** [comment]
Yes that could be ignored as well. dart fix will change it but it doesn't need to changed.

**Comment by provokateurin** [comment]
`no_leading_underscores_for_local_identifiers` should still be changed
