### ISSUE TITLE
Dynamite: validate more types

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1247]
Dynamite should support validating more strict types:
- array lengths ##1056 
	- minItems
	- maxItems 
	- uniqueItems (maybe utilize a Set for this)
- number:
	- minimum/exclusiveMinimum
	- maximum/exclusiveMaximum
	- multipleOf
- enum
	- check the pattern at build time (#1313)

This can all fit nicely into: https://github.com/nextcloud/neon/blob/main/packages/dynamite/dynamite/lib/src/helpers/pattern_check.dart. We must not only consider validating these schemas inside objects but also when uses as a parameter in an operation.

**Comment by provokateurin** [comment]
String enums with patterns are broken:
```json
{
	"type": "string",
	"pattern": "^a$",
	"enum": [
		"a",
		"b"
	]
}
```
The pattern match method is called but the enum it is given is not the expected String.

**Comment by provokateurin** [comment]
Required keys of objects are not checked to be present in the properties keys.
