### ISSUE TITLE
Encrypt the user credentials when stored

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1280]
related to: #793

If we decide to stay with shared_prefs we should consider using sncrypted_shared_prefs (or encrypt them ourselves)

**Comment by provokateurin** [comment]
All shared_preference usage should be encrypted as wight store other sensitive things as well. Won't really impact performance as we use enencrypted sqlite for caching.

**Comment by Leptopoda** [comment]
I looked into this yesterday and it looks like most ecrypted shared prefs implementations are not well maintained. We might need to write a custom wrapper for this.

**Comment by Leptopoda** [comment]
Closing as we decided that the added encryption is not worth the bundle size increase.
Adding it in is trivial so open an issue if you need this functionality.
