### ISSUE TITLE
Some keyword escaping happens in the wrong places

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#1441]
`Type` must be added as a keyword to avoid collisions.
I quickly tried adding it, but then generating leads to these errors:
```log
Error in BuiltValueGenerator for /nextcloud/lib/src/api/files_external.openapi.dart.
Please make the following changes to use EnumClass:

1. Have exactly one constructor: const Mount_$Type._(String name) : super(name); or in Dart>=2.17: const Mount_$Type._(super.name);
2. Add getter: static BuiltSet<Mount_$Type> get values => _$values
3. Add method: static Mount_$Type valueOf(String name) => _$valueOf(name)
4. Have exactly one constructor: const StorageConfig_$Type._(String name) : super(name); or in Dart>=2.17: const StorageConfig_$Type._(super.name);
5. Add getter: static BuiltSet<StorageConfig_$Type> get values => _$values
6. Add method: static StorageConfig_$Type valueOf(String name) => _$valueOf(name)
```
I believe this is generating bad code where `Type` is now also escaped inside the name:
```dart
class Mount_$Type extends EnumClass {
  const Mount_$Type._(super.name);

  /// `dir`
  static const Mount_$Type dir = _$mount$TypeDir;

  /// Returns a set with all values this enum contains.
  // coverage:ignore-start
  static BuiltSet<Mount_$Type> get values => _$mount$TypeValues;
  // coverage:ignore-end

  /// Returns the enum value associated to the [name].
  static Mount_$Type valueOf(String name) => _$valueOfMount_$Type(name);

  /// Returns the serialized value of this enum value.
  String get value => _$jsonSerializers.serializeWith(serializer, this)! as String;

  /// Serializer for Mount_$Type.
  @BuiltValueSerializer(custom: true)
  static Serializer<Mount_$Type> get serializer => const _$Mount_$TypeSerializer();
}
```

@Leptopoda do you mind taking a look? This is breaking the update to the latest specs :/

**Comment by Leptopoda** [comment]
I think you are running into https://github.com/nextcloud/neon/issues/1398

There was a reason why I alsso added the escaping to the enum but can't remember why. I'll take a look.

Maybe a PR for upstream is easier.

**Comment by Leptopoda** [comment]
I've made a PR upstream.
https://github.com/google/built_value.dart/pull/1297

**Comment by provokateurin** [comment]
Yep, looks like your PR will fix it.

**Comment by provokateurin** [comment]
This still happens. With the example above it is not necessary to add the dollar sign because it is in the middle of the name, so we shouldn't do it to keep it more readable.

**Comment by provokateurin** [comment]
At least the code is now correctly generated after your upstream fix.

**Comment by Leptopoda** [comment]
So this is now only cosmetic?
As mentioned above there where reasons why I did this (but I can't remember). I'll dive into it in the coming days.

**Comment by provokateurin** [comment]
Only cosmetic, but it also is a breaking change (see the PR).
