### ISSUE TITLE
Investigate using cross_file over universal_io

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1516]
We might want to drop universal_io over [cross_file](https://pub.dev/packages/cross_file).

1. it's maintained by Google
2. it's more lightweight
3. Other packages like image_picker use it and it might make file handling easier.

Now that we no longer depend on the HttpClient from io.

EDIT: added to the milestone as it would be breaking

**Comment by provokateurin** [comment]
It doesn't support a few things we need, like getting the size without reading the full content, opening a sink to write to it etc.
I don't think it'll work for us :/

**Comment by provokateurin** [comment]
Nope, this is definitely not going to work

**Comment by provokateurin** [comment]
cross_file doesn't support writing any files, which kinda makes sense, but it doesn't cover all of our use-cases.

**Comment by provokateurin** [comment]
Checkout https://github.com/nextcloud/neon/tree/wip-cross_file

**Comment by Leptopoda** [comment]
Meh javascript is just to shitty to support writing streams.
