### ISSUE TITLE
Persist cookies on disk

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#1536]
The cookies should have been stored on disk to allow caching the credentials between runs.

**Comment by provokateurin** [comment]
Ah but it is not so easy to separate the cookies between accounts since one might have multiple accounts on the same server.

**Comment by Leptopoda** [comment]
But shouldn't neon still persist them? Just on a per account basis.
Thankfully the cookie_jar package provides nice abstracted interfaces so we can implement it into our existing sqlite or shared_prefs workflow.

**Comment by provokateurin** [comment]
Yes they should be persisted but separate per account with a custom storage.
