### ISSUE TITLE
Refactor neon storages 

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1538]
replaces: #1280, #793, #1536

Neon currently uses:
- memory based cookie persistence
- shared_preferences based options persistence
- sqlite based request caching

We should:
- [x] migrate all into sqlite (probably separate databases to keep the caches separate from actual data)
- [x] introduce separate interfaces to make switching in the future easier and keep the code separate (our options already use `SettingsStorage` and cookie_jar provides `Storage` so only needed for the cache)
<s> - [ ] use encryption on all storages </s>
<s>- [ ] add a storage version to the shared preference persistence for potential migrations.</s>

This probably requires major restructures and cleanups in the framework as we also expose `SingleValueStorage` a generic key value like storage. We should maybe rethink our key handling as we currently use enums to avoid duplication but we are also nesting this which doesn't scale well.

**Comment by provokateurin** [comment]
We can store the cookies in the same database as the cache as they are only temporary information and can be easily recreated.

**Comment by Leptopoda** [comment]
We should disable both the cookie and request cache for web as this should be handled by the browser.
