### ISSUE TITLE
bug(nextcloud): `unawaited` causes errors to be uncatchable

### ISSUE THREAD

**Issue by florian-obernberger** [nextcloud/neon#1588]
Hey there! I am using the `nextcloud` package to sync some files of my app with NC. Since my app has it's own error management and logging system I am catching (and mapping) all errors thrown by the `NextcloudClient`, especially the `DynamiteException`s.

But I recently noticed that my `try catch` blocks are not catching some of the errors anymore. After some digging I found the root of the problem.

It only occurs in the `WebDAVClient.get` and `WebDAVClient.getStream` methods. Since #1544 the `WebDAVClient._send` method is wrapped by the `unawaited` method. While this allows for the `onProgress` function, it also makes it impossible to catch the `DynamiteStatusException` (and any other Exception) that is thrown by the `_send` method:

https://github.com/nextcloud/neon/blob/cca6e815f3d7dc28796c4ffddfbcc2ee6bd17ed9/packages/nextcloud/lib/src/webdav/client.dart#L228-L262

Here is the relevant snipped of the documentation of the `unawaited` function:

> If the future completes with an error, it was likely a mistake to not await it. That error will still occur and will be considered unhandled unless the same future is awaited (or otherwise handled) elsewhere too. Because of that, `unawaited` should only be used for futures that are *expected* to complete with a value.

This function should not be used here since the future is most definitely expected to throw an error (for eg. when a file is locked (status code 423) or the NC instance is in maintenance or anything else like a missing internet connection or a timeout).

The simplest solution would probably be to just revert the pr, but that would also mean loosing the `onProgress` functionality...

**Comment by provokateurin** [comment]
Thanks for the report, I'm going to take a look

**Comment by provokateurin** [comment]
@florian-obernberger can you test https://github.com/nextcloud/neon/pull/1589 and make sure it works for you as well?

**Comment by florian-obernberger** [comment]
Will do, I'll reply asap :)

**Comment by florian-obernberger** [comment]
So, I quickly tested it by causing 404s to occur and it seems to work as expected! `WebDAVClient.get` now does again throw the errors and by extension `WebDAVClient.getStream` should also work flawlessly again!

Thank you so much for the quick response and resolution! :D

**Comment by provokateurin** [comment]
Awesome, then I'm just waiting for a review of the PR by @Leptopoda and I'll kick off a new release right after merging the fix.

**Comment by florian-obernberger** [comment]
Sounds like a good plan! I'll leave the issue open so it can be closed together with the PR being merged.

**Comment by provokateurin** [comment]
Released in 5.0.1
