### ISSUE TITLE
QR login broken

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1706]
I haven't debugged it much but looks like it's broken.

**Comment by provokateurin** [comment]
Broken in what way? I think the last changes were by you with catching only the specific exception which could be a potential cause.

**Comment by provokateurin** [comment]
Oh yeah I think I once saw something similar but thought it was because of web (which I was working at the time).

**Comment by provokateurin** [comment]
I'm pretty sure we need to have separate routes for with/without credentials. I'm not sure how this worked before as we didn't touch the routing since the QR code login was added.
