### ISSUE TITLE
Investigate chopper

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#175]
See if https://github.com/lejard-h/chopper makes sense for the generated Dart client.

**Comment by provokateurin** [comment]
I haven't checked it out in depth, but I'm pretty sure the effort for migrating to it are not justified and we loose a lot of control about the API. It might not even support everything that we need and honestly I don't want to find that out after refactoring the whole dynamite generator. @Leptopoda do you think we can close this?

**Comment by Leptopoda** [comment]
I really like the idea and I think that it could simplify dynamite in the long turn. Iirc it also has good support for built_value which might simplify a lot of our serialisation code.


I agree that it's probably not justified yet and needs some further investigation.
Maybe we can find some time to just investigate it further at the community meetup?

**Comment by Leptopoda** [comment]
I really like the idea and I think that it could simplify dynamite in the long turn. Iirc it also has good support for built_value which might simplify a lot of our serialisation code.


I agree that it's probably not justified yet and needs some further investigation.
Maybe we can find some time to just investigate it further at the community meetup?

**Comment by provokateurin** [comment]
Good idea

**Comment by Leptopoda** [comment]
Dynamite makes use of many custom features.
Unless there is a real benefit and a shortcoming in our current approach we don't consider such a migration worth it.
We are open to revisit this in the future.
