### ISSUE TITLE
Allow option and bloc resolving through the NeonProvider

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#1765]
NeonProvider should allow to resolve `AppOption`s an `Bloc`s.

For framework blocs the NeonProvider should resolve the active account and based on the requested type access the bloc in question. It might be necessary to change the sub bloc handling of the AccountBloc to allow a generic for lookup.
Regarding the Options and AppBloc the framework might need to inject the AppImplementation 
 into the widget tree so lookup can happen through it.
 
 We must be careful with the disposal of the injected objects:
 - do we want them to be disposed when the widget is destroyed?
 - should we still cache some objects when the app is accessed again?

**Comment by provokateurin** [comment]
https://github.com/nextcloud/neon/pull/2053
