### ISSUE TITLE
getStream() requires content-length

### ISSUE THREAD

**Issue by ercoppa** [nextcloud/neon#1988]
[getStream()](https://github.com/nextcloud/neon/blob/main/packages/nextcloud/lib/src/webdav/client.dart#L300) does not work correctly when the server does not provide the `content-length` header in its response. In particular, when using getStream() from getFile() then I get an empty file. This is true even when using the Neon app.

It seems to be [legal](https://stackoverflow.com/questions/11375507/getting-response-of-http-request-without-content-length) to omit such a header in HTTP: in my case, when the response is chunk-encoded then I do not get the header (I am using latest stable of Nextcloud AIO behind NPM).

**Comment by provokateurin** [comment]
Thanks for reporting!

**Comment by provokateurin** [comment]
Can you test if https://github.com/nextcloud/neon/pull/1989 fixes your problem?

**Comment by ercoppa** [comment]
Yes, it fixes the problem. Thank you.

**Comment by provokateurin** [comment]
Released as 6.1.0
