### ISSUE TITLE
duplicate someOf entries in merged specs

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#2004]
Our specs contain duplicate someOf keys. This shouldn't be an issue but isn't clean either.
@provokateurin should I report this in the extractor?

https://github.com/nextcloud/neon/blob/be923d5/packages/nextcloud/lib/src/api/core.openapi.json#L3557-L3568

**Comment by provokateurin** [comment]
Ah yeah, I'll fix it. You don't need to open another issue for it.

**Comment by provokateurin** [comment]
With the fix applied only the spec is changed but the generated code isn't. Shall we just close the issue and then this fix will come to us later whenever we update the openapi-extractor again?

**Comment by Leptopoda** [comment]
:+1: 
We collect all subtypes into a Set so it doesn't affect us.
