### ISSUE TITLE
Wrong semantic label for drawer icons

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#2273]
https://github.com/nextcloud/neon/blob/4aa7f63ee7f8956a12d4c9ab093689251cb24cff/packages/neon_framework/lib/src/models/app_implementation.dart#L174

They are currently transcribed with `Nextcloud logo` which is wrong.

**Comment by Apocalypse96** [comment]
Hey!! @Leptopoda I would love to solve this issue

**Comment by provokateurin** [comment]
Go for it :)

**Comment by provokateurin** [comment]
Shouldn't this rather be excluded from the semantics as it doesn't convey any meaning if you can't see it? It adds no value if a screenreader reads the label out loud.

**Comment by Leptopoda** [comment]
You're right.
The text label will already be read
