### ISSUE TITLE
Throw exceptions when WebDAV operations return non-success status codes

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#2307]

**Comment by UtkershBasnet** [comment]
I'd like to fix this issue

**Comment by provokateurin** [comment]
Sure, go ahead :) Please make sure to consider the WebDAV specification for which status codes are fine and which are not. In case there is a problem with the status code a `DynamiteStatusCodeException` should be thrown.

**Comment by provokateurin** [comment]
Also make sure to adjusts the tests so they expect the exception where necessary.
