### ISSUE TITLE
Broken analysis in neon_framework with Dart 3.5

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#2391]
The analyzer doesn't show any warnings any more since https://github.com/nextcloud/neon/commit/920cdac6dc3be1deacc348e68b80457fd322f933 (I bisected it).
It seems to be related to Dart 3.5 and maybe the workspace packages, but I haven't found much about it yet. Here are my only findings:
https://github.com/dart-lang/sdk/issues/56416
https://github.com/dart-lang/sdk/issues/56047
https://github.com/dart-lang/sdk/issues/55975
https://github.com/dart-lang/sdk/commit/14ff0ca186110ba3e06737a430016f858fdb2655

So maybe we are lucky and this is fixed in Dart 3.5.1. Until then reverting the update is the only option we have.

**Comment by keertip** [comment]
The fix will be in Dart 3.5.1, do try it out and let us know if it works.

**Comment by provokateurin** [comment]
So with https://github.com/nextcloud/neon/pull/2399 we finally have Dart 3.5.1. I'll give it a test in the next days to see if we can now actually upgrade to Flutter 3.24.

**Comment by provokateurin** [comment]
We might be running into https://github.com/dart-lang/sdk/issues/56475, using flutter master the CI no longer sees the lints that it sees with flutter 3.24.1 which I don't see locally ever.

**Comment by provokateurin** [comment]
Using flutter beta (with Dart 3.6 beta) resolves the linting problems and everything is reproducible again. Dart 3.5.2 would probably be enough already.

**Comment by provokateurin** [comment]
Or not https://github.com/nextcloud/neon/pull/2452...
