### ISSUE TITLE
shareapi.getShares date Deserializing Error

### ISSUE THREAD

**Issue by toly1994328** [nextcloud/neon#2405]
Deserializing to 'ShareapiGetSharesResponseApplicationJson_Ocs' failed due to: Deserializing to 'BuiltList<Share>' failed due to: Deserializing to 'Share' failed due to: Tried to construct class "Share" with null for non-nullable field "label".

The lable of data will be null, but in nextcloud SDK check it  non-nullable 
![image](https://github.com/user-attachments/assets/f8971a8f-a3ce-41af-a400-ce85e1107226)

**Comment by provokateurin** [comment]
Thanks for reporting, can you share the steps for reproducing this error? What endpoints did you call?

**Comment by provokateurin** [comment]
I need more information to figure out what is going wrong.
As far as I can tell the label should never be null as the fallback is just an empty string, so somewhere it is going wrong.

**Comment by provokateurin** [comment]
To  be clear: I expect this to be an upstream issue in the code, not in the OpenAPI documentation or this project.

**Comment by toly1994328** [comment]
I create share on web (not flutter),and use share api on windows desktop, the label is null

**Comment by provokateurin** [comment]
What Nextcloud version are you running and how exactly did you configure the share

**Comment by provokateurin** [comment]
Ok I was able to reproduce the problem. When the share is created and returned the label is an empty string as expected, but when querying the shares afterwards then the label is null.

**Comment by provokateurin** [comment]
This was actually a bug in the code and not just the API documentation: https://github.com/nextcloud/server/pull/48673
