### ISSUE TITLE
Remove Nextcloud 28 support

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#2560]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule EOL end of December.

**Comment by provokateurin** [comment]
I had a look the only changes will be dropping these two patches:
- https://github.com/nextcloud/neon/blob/main/packages/nextcloud/lib/src/api/core/patches/2-compatibility-28.json
- https://github.com/nextcloud/neon/blob/main/packages/nextcloud/lib/src/api/spreed/patches/3-compatibility-18.json
We also only remove these presets:
- https://github.com/nextcloud/neon/blob/main/packages/nextcloud/packages/nextcloud_test_presets/docker/presets/drop_account/2.4
- https://github.com/nextcloud/neon/blob/main/packages/nextcloud/packages/nextcloud_test_presets/docker/presets/notes/4.8
- https://github.com/nextcloud/neon/blob/main/packages/nextcloud/packages/nextcloud_test_presets/docker/presets/server/28.0
- https://github.com/nextcloud/neon/blob/main/packages/nextcloud/packages/nextcloud_test_presets/docker/presets/spreed/18.0

Now I wonder if we should really remove 28 support given that there is basically no added maintenance cost and almost no reduction in CI time.

I also checked what patches we can drop when removing 29 support and it is a quite similar story.
I think we could try to continue to support them for now, until it drastically increases maintenance and CI time.
Other than that there is really no downside for us keeping compatibility for older versions around longer (except for new features, but we can just check their availability at runtime instead of doing that based on the generally supported versions).

CC @Leptopoda what do you think?

**Comment by Leptopoda** [comment]
I completely agree.
As long as it is no maintenance burden, we should try to support them.
I think we should reflect in the readme that we support at least all supported releases (typically the last 3 ones) and try to support whatever is possible.

**Comment by provokateurin** [comment]
Create a PR to adjust it: https://github.com/nextcloud/neon/pull/2668

**Comment by Leptopoda** [comment]
We might want to drop 28 and 29 so we can use non OCS api and remove the webdav hacks.
