### ISSUE TITLE
Use nested router for navigation

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#272]
There are some nasty bugs when popping pages on top of the files browser, but they should be fixable by using another router for the files browser. That should also improve performance when going back a directory, because it doesn't need to be loaded again.

**Comment by Leptopoda** [comment]
How did you imagine this being done?

I think we'll need something similar for a nice implementation of #329. My idea was to use [`go_router`](https://pub.dev/packages/go_router) for routing.

The neon would register a router for things like login, settings ... while every app can itself provide a custom router.
This nested router could then be used to navigate within the app (needed for files and the second panel in a multi layout view).

According to my research go_router can handle both use cases with a [ShellRoute](https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html).

1. can we bump this to a global neon issue?
2. if you like the go_router approach I can have a shot at it :)

**Comment by provokateurin** [comment]
Sure thing!

**Comment by provokateurin** [comment]
@Leptopoda This is done, right?

**Comment by Leptopoda** [comment]
No; only the foundation for it.
I'll tackle this with the adaptive stuff coming soon TM

**Comment by provokateurin** [comment]
Right, can't wait for that :)

The files app should be restructured because the file browser is a single widget right now, but it should be pages that open on top of each other. In the current implementation the whole page also reloads if you go back a folder.
