### ISSUE TITLE
[Bug]: neon clipping notch in landscape

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#294]
![Screenshot_20230505_230700](https://user-images.githubusercontent.com/25266387/236573304-ac46f14a-fdc2-4465-927a-82e9bac7017c.png)

A `SafeArea` should do the trick but we'd need to implement it on a per screen basis.
Also the QuickBar should probably still extend behind the notch

**Comment by provokateurin** [comment]
We should be able to fix this quite easily, no?
