### ISSUE TITLE
neon: better acessibility 

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#300]
1. for screenreaders:
- We currently have a lot of IconButtons without any tooltip.
- some lists may contain invisible a11y nodes (investigation needed)

2. rtl layout
while a lot of things are multi directional by default our drawer/quickbar implementation isn't.

---

Fortunately I'm not in need for a screen reader and I only know ltr languages/layouts so I'm not the best person for this but it's a starting point.

**Comment by provokateurin** [comment]
I would love to work on this, but I have very little experience with these things.

**Comment by provokateurin** [comment]
I found https://docs.flutter.dev/accessibility-and-localization/accessibility which seems to be a nice introduction to the topic regarding flutter.

**Comment by Leptopoda** [comment]
I've already started to rewrite the drawer for #294.

> I found https://docs.flutter.dev/accessibility-and-localization/accessibility which seems to be a nice introduction to the topic regarding flutter.

I've read this a dozen times over the last few years but would still only consider to know the tip of the iceberg.
The talk under https://docs.flutter.dev/accessibility-and-localization/accessibility#building-with-accessibility-in-mind is interesting.

> I hope that it will be possible to 'lint' accessibility issues.

You can test it in unit test :woman_shrugging:

**Comment by Leptopoda** [comment]
I think a great starting point would be to add tooltips to every icon button.
we don't need to wrap it in one like:
https://github.com/provokateurin/nextcloud-neon/blob/a7be31ff2632d02eea7c19afbfb8e6edf2ea473d/packages/neon/neon/lib/src/pages/home.dart#L361

as IconButton already has support for it:
https://api.flutter.dev/flutter/material/IconButton/IconButton.html

**Comment by provokateurin** [comment]
I think the next steps could be adding widget tests for everything (which we should do anyway) and then adding the automatic accessibility checks.

**Comment by Leptopoda** [comment]
Our `ProgressIndicators` should also include a semantic label.
Same for our `NeonValidationTile`

**Comment by Leptopoda** [comment]
Should we close this one?
#2113 Should help a lot and I don't think we can do anything more rn.

**Comment by provokateurin** [comment]
There is probably a lot we could improve, but having this very broad issue doesn't help much with that.
