### ISSUE TITLE
Don't spam servers when unauthenticated

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#365]
When the credentials no longer match we spam the server with requests that result in a 401. The server then throttles the next login because we send so many wrong requests. We should stop sending future requests once we hit one that returned a 401 (for that user). I wonder how other clients are doing this (maybe checking one endpoint before sending any other requests?).

**Comment by provokateurin** [comment]
Of course this doesn't happen often, but when it happens it's very annoying. Right now I only see it when I reset my dev container but still have accounts with old credentials, but this could also happen for users who delete the app password intentionally or accidentally. @Leptopoda should we add it to the 1.0 release?

**Comment by Leptopoda** [comment]
Sound's good.

But probably nothing I'll tackle :)

**Comment by provokateurin** [comment]
I'm removing this again from the milestone. It's quite rare users will hit this and we can always fix it after the first release

**Comment by provokateurin** [comment]
Something to be implemented within neon_http_client.
