### ISSUE TITLE
Systemtray potentially contains unsupported apps

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#431]
1. The systemtray shows a `Notifications` entry that doesn't do anything on my side (probably because I haven't set it up)
2. We unconditionally add all apps supported by the app and don't check for the active account or supported apps.

This is somewhat related to what I mentioned in #423 with the web support.

**Comment by provokateurin** [comment]
Yeah I wasn't sure what the best way is to implement this.
I think we could create submenus and then for each account list the available apps. Then you could also use the tray to just change the active account.

**Comment by provokateurin** [comment]
The same problem exists with the quick actions

**Comment by provokateurin** [comment]
Closing after https://github.com/nextcloud/neon/pull/1391
