### ISSUE TITLE
Improve test/code coverage

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#435]
Currently we test most of the endpoints we use, but don't cover all the different options.
Add more tests to cover all endpoints and all available options.

**Comment by provokateurin** [comment]
This won't be feasible anymore with the automatic specs, but we should at least try to cover the endpoints used by neon.

**Comment by provokateurin** [comment]
For WebDAV I would like to replicate all the tests of https://github.com/notroj/litmus. It is a test suite for testing WebDAV servers for compliance of the spec, but it will help us to cover most WebDAV features and also find possible problems in our implementation.

**Comment by provokateurin** [comment]
For the normal APIs I would like to switch to [gherkin](https://cucumber.io/docs/gherkin/reference/) as apps like [Talk](https://github.com/nextcloud/spreed/tree/master/tests/integration/features) already do it. That will make it possible to write tests independent of the platform/language/client/framework. This way we can share some efforts and don't even need to write any tests for Talk manually since they already exists. There is also a chance that this will become a task I will work on officially in the future.

**Comment by provokateurin** [comment]
There is also [tcases](https://github.com/Cornutum/tcases/tree/master/tcases-openapi) which we can use to generate tests based on the specs. The output is a JSON and we would need to write another generator that can convert that format into Dart tests using the generated API client.
I'm not sure how useful this will be, but I'm pretty sure we could uncover at least some bugs with this and properly scale our code coverage since it will test everything without someone having to write manual tests.

**Comment by provokateurin** [comment]
And we could also think about using test fixtures for the HTTP calls (similarly to how golden tests work for widget rendering). This way we would catch any possible change on the server or client side. I searched for a package that already implements this but couldn't find any.

**Comment by Leptopoda** [comment]
> And we could also think about using test fixtures for the HTTP calls

What exactly do you mean?

**Comment by provokateurin** [comment]
Basically logging all HTTP parameters like request url, headers, body and response headers and body. The tests would compare the values to the saved ones and fail if they differ. Some of the stuff would need to be done using regex since some tests involve fields that contain a timestamp.

It won't help much, just increase the confidence of our testing.

**Comment by provokateurin** [comment]
tcases is an interesting tool, but i don't think it will be of much use since it relies on example data defined in the spec to generate the happy cases, but there is no way for us to inject it other than manual patching which will never scale with generated specs.

**Comment by provokateurin** [comment]
Right now the most important thing in this issue should be the use of gherkin for tests. Of course we can adapt the Talk tests before we use gherkin for all the other tests, but it would be nice to have everything in line.

**Comment by provokateurin** [comment]
As we want to support multiple app and server versions in the future we should setup a test matrix that will run all tests for all supported versions (including minor/patch versions as they sometimes get bug fixes).

**Comment by provokateurin** [comment]
All ideas were either abandoned or implemented. Gherkin isn't really feasible anymore because our test setup is quite complex now.
