### ISSUE TITLE
Performance profiling

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#445]
we should do some performance profiling before we go live.

I just found a few issues on some older devices

Possible optimizations:
- [x] lazily build lists #585 
- [x] pre compile svg images (similar to #589)
- [x] reduce rebuilds #377 
- [x] https://github.com/nextcloud/neon/blob/69d69657907b937866b9716cbdcb361fd91e1589/packages/neon/neon_files/lib/widgets/browser_view.dart#L72-L79

**Comment by provokateurin** [comment]
I always experience the most jank when starting the app. I've also seen that the active app and the active account is set multiple times (both are not distinct but they shouldn't have to be) which probably causes a lot of that. The other thing is the network requests that are all fired at the same time and the deserialization of the responses (including the cached data). The later could be solved by queueing all requests (which will be partialy done with https://github.com/nextcloud/neon/issues/543 anyway).

**Comment by Leptopoda** [comment]
I have a local branch that reworks the files rendering and I cleaned up the code a lot and made it more performant by multiple orders of magnitude.

It currently depends on #377 and maybe the go_router work.

**Comment by provokateurin** [comment]
That sounds great!
