### ISSUE TITLE
Update logo and use adaptive icons

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#447]
The accent color is controlled by the server theming and thus can be quite bad as a background color for the logo. It should just use black or whit depending on the device theme.

**Comment by provokateurin** [comment]
Using adaptive icons generated with flutter_launcher_icons should do the trick.

**Comment by provokateurin** [comment]
Color should be changed to be the Nextcloud blue, but the logo should have a blue background with a white icon.

**Comment by provokateurin** [comment]
https://nextcloud.com/trademarks/ describes how the gradient is done. I can try my best to do some inkscape+imagick trickery, but it's probably a lot harder and using a proper tool would help a lot.

**Comment by Leptopoda** [comment]
The problem isn't how to get a rasterized image from the background but rather how to get a drawable from our current icons.

We get SVGs from the apps upstream source but would need an android vector drawable for monochrome icons (and also preferable for adaptive icons). 
pub.dev has https://pub.dev/packages/svg_to_avd but I don't know how good it is.

**Comment by provokateurin** [comment]
The problem with generating multiple icons will be solved with https://github.com/nextcloud/neon/issues/747
