### ISSUE TITLE
Dependabot not creating PRs

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#488]
For some reason we never got any dependabot PRs after the initial two, although there definitely are updates available. Maybe the config is broken.

**Comment by Leptopoda** [comment]
looks like he is at it again.

Other monorepos hava a similar structure to ours so this could be a problem with using git dependencies between our packages.
https://github.com/firebase/flutterfire/blob/master/.github/dependabot.yml

**Comment by provokateurin** [comment]
Yeah, maybe it tries to upgrade them one-by-one and but then the constraints make it fail. Shall we create a custom GH action that runs `pub upgrade --major-versions` and submits a PR if there are any changes?

**Comment by provokateurin** [comment]
Hm but melos 3.1.1 has been released and we still point to 3.1.0. Could it be that dependabot only creates PRs for major updates? When I created the config I read the documentation and understood it as if dependabot would create PRs for any update by default, but maybe I was wrong.

**Comment by Leptopoda** [comment]
go_router had a major release :(
https://pub.dev/packages/go_router/changelog

**Comment by provokateurin** [comment]
Maybe it works if we point dependabot to each package individually?

A stupid fix that might work would be exporting every dependency from neon, then we don''t need to import them in the app implementations (but this is a really bad idea).

**Comment by Leptopoda** [comment]
> Maybe it works if we point dependabot to each package individually?

Let's try this. It's odd as it looks like dependabot correctly identifies all of them.
![Screenshot 2023-08-09 at 20-51-21 Dependabot · provokateurin_nextcloud-neon](https://github.com/provokateurin/nextcloud-neon/assets/25266387/a07bc220-d36d-4370-b829-50fd9ce891c7)


https://github.com/provokateurin/nextcloud-neon/network/updates/706799417

But the logs indeed only contain packages found in the root pubspec.yaml file :thinking:

**Comment by provokateurin** [comment]
I wanted to debug this locally but I haven't found the time yet
