### ISSUE TITLE
Feature matrix

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#510]
It would be great to have a feature matrix listing all of our implemented features but also the features of other clients like the Android Files and Talk clients and so on. Sadly nothing like it exists yet, neither publicly nor internally.

The feature matrix could also contain the features that we don't support, but that is probably way too much work.
We could start by just maintaining a list of our features and then populating the other clients over time.

For that we would need to know what a feature even is.
A very basic heuristic could be the coverage of API endpoints.
Almost every API endpoint represents at least one feature, but there are also many features that are only client side which would not be covered by this.
For a start just using this heuristic isn't too bad imo.

@Leptopoda what do you think?

**Comment by Leptopoda** [comment]
Sounds like a lot of work but could turn out cool

**Comment by provokateurin** [comment]
Comparison with all the unofficial clients would also be nice (if we implement their functionality). Quick list can be found at https://search.f-droid.org/?q=nextcloud, but I'm pretty sure there are more clients out there.

**Comment by provokateurin** [comment]
Similar to https://github.com/nextcloud/neon/issues/867 we could check which endpoints we use. It doesn't directly relate to features, but should give us a rough idea of the unused endpoints.

**Comment by provokateurin** [comment]
Too much work
