### ISSUE TITLE
get all user's files

### ISSUE THREAD

**Issue by Elevencode** [nextcloud/neon#542]
How can I get all user's files? 

I create client and call `get()` method:

```
final client = NextcloudClient('https://example.com', loginName: 'admin', password: 'password');
final nextcloudFiles = await client.webdav.get('storage');
```
So, request URL:
https://example.com/remote.php/webdav/storage

but files stores on: 
https://example/index.php/apps/files

what I do wrong?

**Comment by provokateurin** [comment]
The files app is just a frontend for the same storage you can access through WebDAV. If you want to list all files for a user recursively you need to set `depth: "infinity"` on the `client.webdav.propfind(...)` request.

**Comment by Elevencode** [comment]
@provokateurin it works! Thank u, Kate!

**Comment by provokateurin** [comment]
No problem :)
