### ISSUE TITLE
Analzye used Android permissions

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#566]
![Screenshot_20230814-091704_Neo Store](https://github.com/nextcloud/neon/assets/26026535/e92a1a49-8511-49ff-9e8d-f09790a6a495)

Check what permissions are actually used and remove the other ones. I think microphone and phone are not something we actually use or require, so the must be pulled in by a dependency.

**Comment by nishp77** [comment]
There's dependency named `permission_handler` under `neon`  however there's nothing in `AndroidManifest.xml`

**Comment by Leptopoda** [comment]
> There's dependency named `permission_handler` under `neon` however there's nothing in `AndroidManifest.xml`

But we can overwrite the permissions in neon. This means we could force disable one.
This is something an app developer should consider regarding the clients (and potentially plugins) they enable.
