### ISSUE TITLE
Don't run CI on draft PRs

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#606]
While GH doesn't support this directly we can limit CI on PRs where a review is requested or even when a review is approved.

This could save quite a lot of CI

**Comment by provokateurin** [comment]
I'm not sure if we really need this anymore with https://github.com/nextcloud/neon/issues/494. The code formatting&linting and tests take maybe 5 minutes and all other workflows are only a few seconds long. I agree that reducing CI time is a good thing, but in the context of the Nextcloud org we are using extremely little of the CI, compared to server or most of the apps in other repos.

**Comment by Leptopoda** [comment]
I agree
