### ISSUE TITLE
Stop using `...[]` pattern (spread list)

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#696]
Please remove the `...[ ]` pattern where possible as it's really inefficient.
I suggest either using a generator function (the `sync*` `yield` stuff, which probably isn't fitting) or add a `categories` variable and conditionally add elements with `categories.add()`

_Originally posted by @Leptopoda in https://github.com/nextcloud/neon/pull/600#discussion_r1311305372_

**Comment by provokateurin** [comment]
Instead external lists should be used.

**Comment by Leptopoda** [comment]
This now only affects `neon*` packages as all other occurrences have already been tackled over time.
I have a local branch that just needs some testing and minor touchups thus assigning it to me.

**Comment by provokateurin** [comment]
We could add a CI script regex that checks for this. Though there are some legitimate uses (but maybe we can avoid all of them?)

**Comment by Leptopoda** [comment]
I think we can avoid most of them as you might be able to see in my upcoming PR (I'll make a draft shortly).

I don't think CI is needed. The dashboard app is the first one developed to our current code style and standard and it already doesn't make use of this pattern. And for now you can count on my reviews as I really hate this pattern when missused.

**Comment by Leptopoda** [comment]
I don't think that this needs to be in the first app release.
It should be in the neon_framework release but the remaining performance implications are minor and it is easier to tackle this issue differently (unified loading indicator and reworking the settings screen would remove most of the remaining cases)

**Comment by provokateurin** [comment]
This is rarely used anymore and the few remaining places are not performance sensitive.
