### ISSUE TITLE
Apk size analysis

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#727]
Initial findings:
- the nextcloud package is 1.9MB
  - the serializers are ~8%
- flutter_zxing also bundles zxing versions for other abis (~850KB per abi => 2.5MB) (https://github.com/khoren93/flutter_zxing/issues/107)
- https://github.com/fluttercommunity/wakelock_plus/issues/5 (~4.5 KB)
- default-source.svg.vec is disproportionally large to otherserver icons (650KB from 720KB) https://github.com/nextcloud/neon/pull/729
- #726 
- Precompile all SVGs https://github.com/nextcloud/neon/pull/731

[apk-code-size-analysis_01.json.txt](https://github.com/nextcloud/neon/files/12548461/apk-code-size-analysis_01.json.txt)

**Comment by provokateurin** [comment]
looking at https://github.com/nextcloud/server/blob/master/apps/theming/img/default-source.svg it seems like we shouldn't include because it's a whole screenshot inside an svg

**Comment by provokateurin** [comment]
Can we close this? The problems are tracked upstream and if those get fixed we will automatically get the benefits without having to put in any work on our side.
