### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#732]
https://github.com/nextcloud/android/issues/11950

**Comment by provokateurin** [comment]
Neat, https://framagit.org/framasoft/nextcloud/drop_account already makes use of openapi-extractor (although they haven't pinned it in their composer.json).

**Comment by provokateurin** [comment]
Ok it relies on https://github.com/nextcloud/neon/issues/1492 and technically needs to have support for multiple status codes (with different body schemas), but other than that it will be fairly easy to add. I already have generated everything locally, but since we can't use it yet there is no point in adding it already.

**Comment by provokateurin** [comment]
The mobile apps just redirect to the webpage because of the password confirmation problem, @Leptopoda shall we do the same until we can use the endpoint?

**Comment by Leptopoda** [comment]
we'll need to do this anyways in case the app is not installed on the server (as a fallback)

**Comment by provokateurin** [comment]
If the app is not installed on the server there is actually no way to delete your own account. The app is the only way (other than CLI), but this isn't really a problem since the client can't do anything about it (and so can't the other mobile clients).
