### ISSUE TITLE
Just a query of some questions

### ISSUE THREAD

**Issue by nishp77** [nextcloud/neon#746]
Hi I was also thinking of writing a client for desktop side using compose-desktop just to learn on the side because I like writing UI in declarative form.

So is this project going to target all clients? Not web?
Is this project more of SDK?

**Comment by Leptopoda** [comment]
Hi there,
this project currently has three main goals:
1. be a cross platform Nextcloud client that runs on iOS, Android, MacOS, Windows, Linux and Web. We already support Android and Linux with the other platforms hopefully coming shortly (if you have the knowledge and want to help feel free to open a PR)
2. we are a Nextcloud client framework. This means that people wanting to develop a custom app for nextcloud (maybe leveraging multiple server apps) we already have the done the heavy lifting (account management, caching and the data flow)
3. we are a multi client app. This means you can have the files app, news app and other in one single app  on your phone/pc.

To make this work we also provide other tools like a dart client for nextcloud apis.
We'll both have a talk and a workshop at the Nextcloud conference next week and will also publish the slides afterwards.

**Comment by provokateurin** [comment]
@nishp77 out of curiosity, how did you find this project?

**Comment by nishp77** [comment]
To be honest, I started contributing to open source back in 2019 that's how I landed my first job however shifted later for private firm JustEatTakeaway then went to Neo Financial but got laid off currently work as contractor but I'm not enjoying. I made my first swift app 2 months ago that's more like Uber... Since then I want to go back to contributing and make apps for linux side so today morning was like make a list of projects to contribute, I knew nextcloud tried wayback to contribute but I always get stuck somewhere then lose hope because don't know much about PHP, plus I'm contributing on GitNuro similar to gitkraken, wanted to kotlin with compose UI they use flutter skia library underneath. Don't like qml way or web of writing UI though I love to draw, so yeah everyday I keep reading articles or finding projects on github so that I how I found this...

**Comment by provokateurin** [comment]
We will happly accept contributions if you decide to work and learn on this. Do you have any more questions?

**Comment by provokateurin** [comment]
@nishp77 can we close the issue?
