### ISSUE TITLE
Disable mark all notifications as read button when no notifications are available

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#774]

**Comment by Sanskar2807** [comment]
Hi @provokateurin 
I would like to work on this issue.

**Comment by Leptopoda** [comment]
Feel free to reach out if you need and help.

**Comment by Leptopoda** [comment]
using the run button in your IDE (vs-code or intellij) should also just work

**Comment by provokateurin** [comment]
@Sanskar2807 Do you need help with this? Please let us know if we can assist you in some way.
