### ISSUE TITLE
refactor client packges (Imports and exports)

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#784]
Currently our clients are all single files using the `part` directive.

Use a normal package approach

**Comment by provokateurin** [comment]
And the code should be moved to an src/ folder inside the lib/ folder.

**Comment by Nkiriobasi** [comment]
Is this free? I’ll like to fix it.

**Comment by provokateurin** [comment]
@Nkiriobasi sure! Thanks for picking this up :)

**Comment by provokateurin** [comment]
@Nkiriobasi Do you need help with this? Please let us know if we can assist you in some way.
