### ISSUE TITLE
Use Iterable instead of List for array request parameters

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#842]
Makes it a bit easier to work with since List adds some unnecessary restrictions.

**Comment by Leptopoda** [comment]
We need to look out for the serializers and their registered builders when changing the types.

**Comment by provokateurin** [comment]
Yeah, I think this doesn't actually make a lot of sense. If we allow passing any iterable we still need to do the conversion somewhere. Better to let the consumer handle it instead of the library. What do you think?

**Comment by Leptopoda** [comment]
I think the easiest way would be to just use built_collection throughout the framework.

They are immutable and usually less error prone (immutable -> no side effects)

**Comment by provokateurin** [comment]
Agreed, but I remember there was a problem when we used them in our parameters when we used BuiltList instead of List. I think it had something to do with default values :thinking:

**Comment by Leptopoda** [comment]
#1292 will switch to BuiltList and after #1278 we will no longer support non built_collection values.
I don't think that this issue makes sense.

**Comment by provokateurin** [comment]
Agreed
