### ISSUE TITLE
Remove Scrollbars

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#861]
Scrollbars are now automatically applied, so we don't need to add them in our code anymore: https://docs.flutter.dev/release/breaking-changes/default-desktop-scrollbars

**Comment by betusin** [comment]
Hi! This is my first contribution and since I do not know anything about this project, could you please provide some more information about where to find the Scrollbars that need to be removed? I would like to help with this issue!

**Comment by provokateurin** [comment]
You can search for all scrollbar widgets in the project using the term `ScrollBar(`. I think there are only a few that are left anyways

**Comment by Leptopoda** [comment]
@betusin 
We also have some information on how to set up your development environment in [CONTRIBUTING.md](https://github.com/nextcloud/neon/blob/main/CONTRIBUTING.md)

**Comment by Redvey** [comment]
Can u please assign me as well?
