### ISSUE TITLE
Setup CI for checking unused dependencies

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#921]
https://pub.dev/packages/dependency_validator

**Comment by Leptopoda** [comment]
I did investigate this a few weeks ago and I can not say that this tool is that good.
It can be great to manually check dependencies every now and then but I doubt that it can be used in CI.
Sadly it does not take package borders into account so nested packages (like the example packages) will create false positives. An issue is already opened upstream but there is little momentum in the package overall.
